#Adjust the values to the following arguments
samples_file: "path_to_samples.csv_file"
output_dir: "results/" #"path_to_desired_results"
reference_file: "Path_to_reference_genome_file"

pbmm2_alignment:
  mode: "HIFI"
