# Snakemake SLURM Profile Configuration
executor: slurm
jobs: 4
use-conda: true
printshellcmds: true
software-deployment-method: conda

default-resources:
  runtime: 60
  mem_mb: 4000

latency-wait: 60
rerun-incomplete: true
printshellcmds: false